name: Daily Automation Update

on:
  schedule:
    # Runs 6 times a day, every 120 mins (2 hours) 
    # Starts at 22:00 UTC (4:00 AM GMT+6)
    - cron: '0 22,0,2,4,6,8 * * *'
  workflow_dispatch: # Allows you to run it manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to v4 for better performance

      - name: Force Re-deployment
        run: |
          git config --local user.email "hassanbiswas.github.io@gmail.com"
          git config --local user.name "Hassan Biswas"
          git commit --allow-empty -m "Daily automated logic pulse [${{ github.run_id }}]"
          git push
          
